# Generated by Django 4.0.3 on 2022-06-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkbotapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_history',
            old_name='cUID',
            new_name='cUid',
        ),
    ]
